export const AnimationList = [
  { name: '애니메이션1', id: 1, src: 'sa-animation sa-fade-up' },
  { name: '애니메이션2', id: 2, src: 'sa-animation sa-fade-down' },
  { name: '애니메이션3', id: 3, src: '' },
  { name: '애니메이션4', id: 4, src: '' },
  { name: '애니메이션5', id: 5, src: '' },
  { name: '애니메이션6', id: 6, src: '' },
  { name: '애니메이션7', id: 7, src: '' },
  { name: '애니메이션8', id: 8, src: '' },
  { name: '애니메이션9', id: 9, src: '' },
  { name: '애니메이션10', id: 10, src: '' },
  { name: '애니메이션11', id: 11, src: '' },
  { name: '애니메이션12', id: 12, src: '' },
  { name: '애니메이션13', id: 13, src: '' },
  { name: '애니메이션14', id: 14, src: '' },
  { name: '애니메이션15', id: 15, src: '' },
  { name: '애니메이션16', id: 16, src: '' },
  { name: '애니메이션17', id: 17, src: '' },
  { name: '애니메이션18', id: 18, src: '' },
  { name: '애니메이션19', id: 19, src: '' },
  { name: '애니메이션20', id: 20, src: '' },
  { name: '애니메이션21', id: 21, src: '' },
];
