export const AnimationList = [
  { name: '애니메이션1', id: 1 },
  { name: '애니메이션2', id: 2 },
  { name: '애니메이션3', id: 3 },
  { name: '애니메이션4', id: 4 },
  { name: '애니메이션5', id: 5 },
  { name: '애니메이션6', id: 6 },
  { name: '애니메이션7', id: 7 },
  { name: '애니메이션8', id: 8 },
  { name: '애니메이션9', id: 9 },
  { name: '애니메이션10', id: 10 },
  { name: '애니메이션11', id: 11 },
  { name: '애니메이션12', id: 12 },
  { name: '애니메이션13', id: 13 },
  { name: '애니메이션14', id: 14 },
  { name: '애니메이션15', id: 15 },
  { name: '애니메이션16', id: 16 },
  { name: '애니메이션17', id: 17 },
  { name: '애니메이션18', id: 18 },
  { name: '애니메이션19', id: 19 },
  { name: '애니메이션20', id: 20 },
  { name: '애니메이션21', id: 21 },
];
