export const AnimationList = [
  { name: 'fade-up', id: 1, src: 'sa-animation sa-fade-up' },
  { name: 'fade-down', id: 2, src: 'sa-animation sa-fade-down' },
  { name: 'fade-left', id: 3, src: 'sa-animation sa-fade-left' },
  { name: 'fade-right', id: 4, src: 'sa-animation sa-fade-right' },
  { name: 'fade-up-right', id: 5, src: 'sa-animation sa-fade-up' },
  { name: 'fade-up-left', id: 6, src: 'sa-animation sa-fade-down' },
  { name: 'fade-down-right', id: 7, src: 'sa-animation sa-fade-left' },
  { name: 'fade-down-left', id: 8, src: 'sa-animation sa-fade-right' },
  { name: 'scale', id: 9, src: 'sa-animation sa-fade-up' },
  { name: 'scale-x', id: 10, src: 'sa-animation sa-fade-down' },
  { name: 'scale-y', id: 11, src: 'sa-animation sa-fade-left' },
  // { name: '애니메이션12', id: 12, src: 'sa-animation sa-fade-right' },
  // { name: '애니메이션13', id: 13, src: 'sa-animation sa-fade-up' },
  // { name: '애니메이션14', id: 14, src: 'sa-animation sa-fade-down' },
  // { name: '애니메이션15', id: 15, src: 'sa-animation sa-fade-left' },
  // { name: '애니메이션16', id: 16, src: 'sa-animation sa-fade-right' },
  // { name: '애니메이션17', id: 17, src: 'sa-animation sa-fade-up' },
  // { name: '애니메이션18', id: 18, src: 'sa-animation sa-fade-down' },
  // { name: '애니메이션19', id: 19, src: 'sa-animation sa-fade-left' },
  // { name: '애니메이션20', id: 20, src: 'sa-animation sa-fade-right' },
  // { name: '애니메이션21', id: 21, src: 'sa-animation sa-fade-up' },
];
